version: '3.7'
services:
  microservice-email:
    image: vladimirmyshkovski/microservice-email
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: microservice_email
    hostname: microservice_email
    ports:
      - "8080:8080"
    volumes:
      - ../:/code
    environment:
      - PORT=8080
    links:
      - rabbitmq:rabbitmq_server

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
